#!/bin/sh
echo "F**k you shutdown Installer for Linux"
echo "installing..."
sudo mv fuckyou.sh /opt/
sudo ln -s /opt/fuckyou.sh /usr/local/bin/fuckyou
echo "done!"
echo "$ shutdown now to shutdown your PC"
